#!/usr/bin/env bash
# ==============================================================================
# generate_matrix.sh — Generate GitLab CI parallel job matrix from clusters.yml
# ==============================================================================
# Reads the cluster inventory and outputs a JSON array suitable for GitLab CI
# parallel:matrix dynamic child pipeline or dotenv artifacts.
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/helpers.sh"

CONFIG_FILE="${CONFIG_FILE:-config/clusters.yml}"

main() {
  local all_clusters
  all_clusters=$(parse_clusters "$CONFIG_FILE")

  # Apply CLUSTER_FILTER (defaults to "all" if not set)
  local clusters
  clusters=$(filter_clusters "$all_clusters")

  local count
  count=$(echo "$clusters" | jq length)
  log_info "Generating matrix for ${count} cluster(s) (filter: ${CLUSTER_FILTER:-all})"

  # Output as GitLab CI dotenv format — one variable per cluster
  # This will be sourced into the pipeline as a child pipeline config
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local name cluster_name region role_arn namespace secret_name secret_key
    name=$(echo "$cluster" | jq -r '.name')
    cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    region=$(echo "$cluster" | jq -r '.aws_region')
    role_arn=$(echo "$cluster" | jq -r '.role_arn')
    namespace=$(echo "$cluster" | jq -r '.namespace')
    secret_name=$(echo "$cluster" | jq -r '.secret_name')
    secret_key=$(echo "$cluster" | jq -r '.secret_key')

    echo "${name}|${cluster_name}|${region}|${role_arn}|${namespace}|${secret_name}|${secret_key}"
  done > "${CI_PROJECT_DIR:-$(pwd)}/cluster_matrix.txt"

  # Also generate the child pipeline YAML for dynamic parallel jobs
  generate_child_pipeline "$clusters"

  log_info "Matrix generated: cluster_matrix.txt and child-pipeline.yml"
}

generate_child_pipeline() {
  local clusters="$1"
  local output="${CI_PROJECT_DIR:-$(pwd)}/child-pipeline.yml"

  cat > "$output" << 'HEADER'
# Auto-generated child pipeline — DO NOT EDIT
# Generated by generate_matrix.sh

stages:
  - rollout

.rollout_template:
  stage: rollout
  tags:
    - EKS_RUNNER_GITLAB
  variables:
    GIT_SSL_NO_VERIFY: "true"
    ROTATION_STATE_FILE: "${CI_PROJECT_DIR}/rotation_state.json"
  before_script:
    - source scripts/helpers.sh
  script:
    - |
      export CLUSTER_NAME="${CLUSTER_NAME}"
      export AWS_REGION="${AWS_REGION}"
      export ROLE_ARN="${ROLE_ARN}"
      export K8S_NAMESPACE="${K8S_NAMESPACE}"
      export K8S_SECRET_NAME="${K8S_SECRET_NAME}"
      export K8S_SECRET_KEY="${K8S_SECRET_KEY}"
      bash scripts/rollout.sh
  retry:
    max: 2
    when: script_failure
  timeout: 10m

HEADER

  # Generate one job per cluster
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local name cluster_name region role_arn namespace secret_name secret_key
    name=$(echo "$cluster" | jq -r '.name')
    cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    region=$(echo "$cluster" | jq -r '.aws_region')
    role_arn=$(echo "$cluster" | jq -r '.role_arn')
    namespace=$(echo "$cluster" | jq -r '.namespace')
    secret_name=$(echo "$cluster" | jq -r '.secret_name')
    secret_key=$(echo "$cluster" | jq -r '.secret_key')

    cat >> "$output" << EOF
rollout-${name}:
  extends: .rollout_template
  variables:
    CLUSTER_NAME: "${cluster_name}"
    AWS_REGION: "${region}"
    ROLE_ARN: "${role_arn}"
    K8S_NAMESPACE: "${namespace}"
    K8S_SECRET_NAME: "${secret_name}"
    K8S_SECRET_KEY: "${secret_key}"

EOF
  done
}

main "$@"
