#!/usr/bin/env bash
# ==============================================================================
# generate_matrix.sh — Generate GitLab CI parallel job matrix from clusters.json
# ==============================================================================
# Reads the cluster inventory and outputs:
#   - child-pipeline.yml  — one job per cluster with the new API key baked in
#   - cluster_matrix.txt  — pipe-delimited list for reference
#
# Filtering (applied in order):
#   1. DD_ENV         — Only clusters where .environment == DD_ENV (safety gate)
#   2. CLUSTER_FILTER — Further filter by name, tag:X, or tag:X+Y (optional)
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/helpers.sh"

CONFIG_FILE="${CONFIG_FILE:-config/clusters.json}"
DD_ENV="${DD_ENV:-}"

main() {
  local all_clusters
  all_clusters=$(parse_clusters "$CONFIG_FILE")

  # Step 1: Filter by DD_ENV — this is the primary safety gate.
  # A prod rotation pipeline must ONLY update prod clusters, never lower/ist/uat.
  if [[ -n "$DD_ENV" && "$DD_ENV" != "all" ]]; then
    local env_count_before
    env_count_before=$(echo "$all_clusters" | jq length)

    all_clusters=$(echo "$all_clusters" | jq -c --arg env "$DD_ENV" \
      '[.[] | select(.environment == $env)]')

    local env_count
    env_count=$(echo "$all_clusters" | jq length)
    log_info "DD_ENV filter '${DD_ENV}': ${env_count}/${env_count_before} clusters matched"

    if [[ "$env_count" -eq 0 ]]; then
      log_error "No clusters found with environment='${DD_ENV}' in ${CONFIG_FILE}"
      log_error "Add 'environment': '${DD_ENV}' to the relevant cluster entries."
      exit 1
    fi
  else
    log_warn "DD_ENV is not set — processing ALL clusters across all environments."
    log_warn "Set DD_ENV in the pipeline schedule for environment-scoped rotation."
  fi

  # Step 2: Apply CLUSTER_FILTER (further narrows within the DD_ENV scope)
  local clusters
  clusters=$(filter_clusters "$all_clusters")

  local count
  count=$(echo "$clusters" | jq length)
  log_info "Generating matrix for ${count} cluster(s) [env=${DD_ENV:-all}, filter=${CLUSTER_FILTER:-all}]"

  # Write pipe-delimited reference file
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local job_name;     job_name=$(echo "$cluster"     | jq -r '.name')
    local cluster_name; cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    local region;       region=$(echo "$cluster"       | jq -r '.aws_region')
    local role_arn;     role_arn=$(echo "$cluster"     | jq -r '.role_arn')
    local namespace;    namespace=$(echo "$cluster"    | jq -r '.namespace')
    local secret_name;  secret_name=$(echo "$cluster"  | jq -r '.secret_name')
    local secret_key;   secret_key=$(echo "$cluster"   | jq -r '.secret_key')
    echo "${job_name}|${cluster_name}|${region}|${role_arn}|${namespace}|${secret_name}|${secret_key}"
  done > "${CI_PROJECT_DIR:-$(pwd)}/cluster_matrix.txt"

  generate_child_pipeline "$clusters"

  log_info "Matrix generated: cluster_matrix.txt and child-pipeline.yml"
}

generate_child_pipeline() {
  local clusters="$1"
  local output="${CI_PROJECT_DIR:-$(pwd)}/child-pipeline.yml"

  # Read the new API key from rotation_state.json (written by rotate_key.sh)
  local rotation_state="${CI_PROJECT_DIR:-$(pwd)}/rotation_state.json"
  local new_api_key
  if [[ -f "$rotation_state" ]]; then
    new_api_key=$(jq -r '.new_key' "$rotation_state")
    log_info "Read new API key from rotation_state.json (last4: ${new_api_key: -4})"

    if [[ -z "$new_api_key" || "$new_api_key" == "null" ]]; then
      log_error "new_key in rotation_state.json is empty or null!"
      jq '.' "$rotation_state"
      exit 1
    fi

    # Sanity check: must not be a variable reference
    if [[ "$new_api_key" == *"GITLAB"* || "$new_api_key" == *"TOKEN"* || \
          "$new_api_key" == *'$'* || "$new_api_key" == *"{"* ]]; then
      log_error "new_key contains a variable reference instead of the actual key value!"
      log_error "Value: ${new_api_key}"
      exit 1
    fi
  else
    log_error "rotation_state.json not found — cannot generate child pipeline"
    log_error "Ensure rotate-api-key or prepare-rollout-only job ran first."
    exit 1
  fi

  # Write child pipeline header with the new key baked into the template
  {
    echo "# Auto-generated child pipeline — DO NOT EDIT"
    echo "# Generated by generate_matrix.sh for env=${DD_ENV:-unknown}"
    echo ""
    echo "stages:"
    echo "  - rollout"
    echo ""
    echo ".rollout_template:"
    echo "  stage: rollout"
    echo "  tags:"
    echo "    - EKS_RUNNER_GITLAB"
    echo "  variables:"
    echo "    GIT_SSL_NO_VERIFY: \"true\""
    printf '    NEW_DD_API_KEY: "%s"\n' "$new_api_key"
    echo "  before_script:"
    echo "    - source scripts/helpers.sh"
    echo "  script:"
    echo "    - bash scripts/rollout.sh"
    echo "  timeout: 15m"
    echo "  allow_failure: true"
    echo ""
  } > "$output"

  # Verify the key was written correctly (last4 check only — no full key in logs)
  local written_key
  written_key=$(grep "NEW_DD_API_KEY" "$output" | sed 's/.*: "//;s/"//')
  log_info "Verified NEW_DD_API_KEY in child-pipeline.yml (last4: ${written_key: -4})"

  # Generate one job per cluster
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local cluster_name; cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    local job_name;     job_name=$(echo "$cluster"     | jq -r '.name')
    local region;       region=$(echo "$cluster"       | jq -r '.aws_region')
    local role_arn;     role_arn=$(echo "$cluster"     | jq -r '.role_arn')
    local namespace;    namespace=$(echo "$cluster"    | jq -r '.namespace')
    local secret_name;  secret_name=$(echo "$cluster"  | jq -r '.secret_name')
    local secret_key;   secret_key=$(echo "$cluster"   | jq -r '.secret_key')

    # Base64-encode extra_secrets JSON so it survives being a CI variable value
    local extra_secrets_json; extra_secrets_json=$(echo "$cluster" | jq -c '.extra_secrets // []')
    local extra_secrets_b64;  extra_secrets_b64=$(printf '%s' "$extra_secrets_json" | base64 | tr -d '\n')

    cat >> "$output" << EOF
rollout-${job_name}:
  extends: .rollout_template
  variables:
    CLUSTER_NAME: "${cluster_name}"
    AWS_REGION: "${region}"
    ROLE_ARN: "${role_arn}"
    K8S_NAMESPACE: "${namespace}"
    K8S_SECRET_NAME: "${secret_name}"
    K8S_SECRET_KEY: "${secret_key}"
    EXTRA_SECRETS_B64: "${extra_secrets_b64}"

EOF
  done
}

main "$@"
