#!/usr/bin/env bash
# ==============================================================================
# generate_matrix.sh — Generate GitLab CI parallel job matrix from clusters.json
# ==============================================================================
# Reads the cluster inventory and outputs a JSON array suitable for GitLab CI
# parallel:matrix dynamic child pipeline or dotenv artifacts.
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/helpers.sh"

CONFIG_FILE="${CONFIG_FILE:-config/clusters.json}"

main() {
  local all_clusters
  all_clusters=$(parse_clusters "$CONFIG_FILE")

  # Apply CLUSTER_FILTER (defaults to "all" if not set)
  local clusters
  clusters=$(filter_clusters "$all_clusters")

  local count
  count=$(echo "$clusters" | jq length)
  log_info "Generating matrix for ${count} cluster(s) (filter: ${CLUSTER_FILTER:-all})"

  # Output as GitLab CI dotenv format — one variable per cluster
  # This will be sourced into the pipeline as a child pipeline config
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local name cluster_name region role_arn namespace secret_name secret_key
    name=$(echo "$cluster" | jq -r '.name')
    cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    region=$(echo "$cluster" | jq -r '.aws_region')
    role_arn=$(echo "$cluster" | jq -r '.role_arn')
    namespace=$(echo "$cluster" | jq -r '.namespace')
    secret_name=$(echo "$cluster" | jq -r '.secret_name')
    secret_key=$(echo "$cluster" | jq -r '.secret_key')

    echo "${name}|${cluster_name}|${region}|${role_arn}|${namespace}|${secret_name}|${secret_key}"
  done > "${CI_PROJECT_DIR:-$(pwd)}/cluster_matrix.txt"

  # Also generate the child pipeline YAML for dynamic parallel jobs
  generate_child_pipeline "$clusters"

  log_info "Matrix generated: cluster_matrix.txt and child-pipeline.yml"
}

generate_child_pipeline() {
  local clusters="$1"
  local output="${CI_PROJECT_DIR:-$(pwd)}/child-pipeline.yml"

  # Read the new API key from rotation state (created by rotate stage)
  local rotation_state="${CI_PROJECT_DIR:-$(pwd)}/rotation_state.json"
  local new_api_key
  if [[ -f "$rotation_state" ]]; then
    new_api_key=$(jq -r '.new_key' "$rotation_state")
    log_info "Read new API key from rotation_state.json (last4: ${new_api_key: -4})"
  else
    log_error "rotation_state.json not found — cannot generate child pipeline"
    exit 1
  fi

  # Write the header — use printf to inject the actual key value
  {
    echo "# Auto-generated child pipeline — DO NOT EDIT"
    echo "# Generated by generate_matrix.sh"
    echo ""
    echo "stages:"
    echo "  - rollout"
    echo ""
    echo ".rollout_template:"
    echo "  stage: rollout"
    echo "  tags:"
    echo "    - EKS_RUNNER_GITLAB"
    echo "  variables:"
    echo "    GIT_SSL_NO_VERIFY: \"true\""
    printf '    NEW_DD_API_KEY: "%s"\n' "$new_api_key"
    echo "  before_script:"
    echo "    - source scripts/helpers.sh"
    echo "  script:"
    echo "    - bash scripts/rollout.sh"
    echo "  retry:"
    echo "    max: 2"
    echo "    when: script_failure"
    echo "  timeout: 10m"
    echo ""
  } > "$output"

  # Verify the key was written (show last 4 only)
  local written_key
  written_key=$(grep "NEW_DD_API_KEY" "$output" | sed 's/.*: "//;s/"//')
  log_info "Verified NEW_DD_API_KEY in child-pipeline.yml (last4: ${written_key: -4})"

  # Generate one job per cluster
  echo "$clusters" | jq -c '.[]' | while IFS= read -r cluster; do
    local name cluster_name region role_arn namespace secret_name secret_key
    name=$(echo "$cluster" | jq -r '.name')
    cluster_name=$(echo "$cluster" | jq -r '.cluster_name')
    region=$(echo "$cluster" | jq -r '.aws_region')
    role_arn=$(echo "$cluster" | jq -r '.role_arn')
    namespace=$(echo "$cluster" | jq -r '.namespace')
    secret_name=$(echo "$cluster" | jq -r '.secret_name')
    secret_key=$(echo "$cluster" | jq -r '.secret_key')

    cat >> "$output" << EOF
rollout-${name}:
  extends: .rollout_template
  variables:
    CLUSTER_NAME: "${cluster_name}"
    AWS_REGION: "${region}"
    ROLE_ARN: "${role_arn}"
    K8S_NAMESPACE: "${namespace}"
    K8S_SECRET_NAME: "${secret_name}"
    K8S_SECRET_KEY: "${secret_key}"

EOF
  done
}

main "$@"
